services:
  api:
    image: node:24-alpine
    tty: true
    stdin_open: true
    user: node
    working_dir: /home/node/app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
    volumes:
      - .:/home/node/app
    env_file:
      - .env.development.local
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    env_file:
      - .env.development.local
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U consignart']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata_dev:
